---
abstract: 'a Perl wrapper around F<libasyncns>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::PkgConfig: 0
  Module::Build: 0
  Module::Build::Compat: 0
  Test::Identity: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  ExtUtils::CChecker: 0.04
  ExtUtils::PkgConfig: 0
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LibAsyncNS
provides:
  Net::LibAsyncNS:
    file: lib/Net/LibAsyncNS.pm
    version: 0.01
  Net::LibAsyncNS::Constants:
    file: lib/Net/LibAsyncNS/Constants.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
